### ISSUE TITLE
Do not panic

### ISSUE THREAD

**Issue by bbrodriges** [mrknow-all/go-oae#2]
Consider not to panic in exported functions/methods as per one of Go proverbs: [Don't panic](https://github.com/golang/go/wiki/CodeReviewComments#dont-panic). Yes it will be a breaking change, but it is better to do before first stable release.

**Comment by mrknow-all** [comment]
Thank you for your suggestion. One of the `panic`s is in the internal struct `failingSeeker` and cannot be triggered by the external code. I have fixed the other panics in https://github.com/mrknow-all/go-oae/commit/1cf0c51a2b72fe2d0dc89387abe1c5ed54f1aa82
